#!/usr/bin/env python3
"""
Signal Shop — spend earned Signal on cosmetic Tidepal goods.

Critical invariant: lifetime Signal NEVER decreases. Tiers, pet growth
stages, and achievements all run on gross lifetime earned (the `rewards`
ledger). The shop spends from a *spendable balance*:

    spendable = gross_lifetime_earned − gross_shop_spent

Every spend is a signed, idempotent, ledger-recorded transaction in
`shop_purchases` (append-only). The price is recorded on the row, so
spendable is always computed server-side — never trusted from a client.

v1 catalog (all cosmetic):
  - 3 accessories (SVG overlays rendered on the pet portrait everywhere):
      acc:sailor_hat (25), acc:star_shades (30), acc:pearl_crown (40)
  - rename_token (20, consumable — renames past the first free one cost one)
  - bypass:<species> (150 — buys a locked species' unlock condition;
      never bypasses one-pet-per-identity)

Anti-gaming: signed endpoints only, server-side balance math, no negative
balances, UNIQUE(fm_id, ref_id) makes double-spends impossible.
"""

import json
import sqlite3
import time

from db import now

SHOP_VERSION = "shop-v1"

# --- catalog ----------------------------------------------------------------
# kind: accessory (one-time, equips to a slot), consumable (repeat-buy),
#       bypass (one-time per locked species).
SHOP_ITEMS = {
    "acc:sailor_hat": {
        "name": "Sailor Hat",
        "kind": "accessory",
        "slot": "head",
        "price": 25,
        "description": "A crisp little sailor cap, worn at a jaunty angle.",
    },
    "acc:star_shades": {
        "name": "Star Shades",
        "kind": "accessory",
        "slot": "face",
        "price": 30,
        "description": "Star-shaped sunglasses. Instant cool.",
    },
    "acc:pearl_crown": {
        "name": "Pearl Crown",
        "kind": "accessory",
        "slot": "head",
        "price": 40,
        "description": "A tiny golden crown set with pearls. Royalty, but make it tide.",
    },
    "rename_token": {
        "name": "Rename Token",
        "kind": "consumable",
        "price": 20,
        "description": ("Your first rename is free. After that, each rename "
                        "costs one token."),
    },
}

BYPASS_PRICE = 150

SHOP_SCHEMA = """
CREATE TABLE IF NOT EXISTS shop_purchases (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  fm_id      TEXT NOT NULL,
  item       TEXT NOT NULL,
  price      INTEGER NOT NULL,          -- price paid, recorded at purchase
  ref_id     TEXT NOT NULL,             -- idempotency key
  created_at INTEGER NOT NULL,
  UNIQUE(fm_id, ref_id)
);
CREATE INDEX IF NOT EXISTS idx_shop_purchases_fm ON shop_purchases(fm_id);

-- cosmetic state per identity (separate table: never touches tidepals)
CREATE TABLE IF NOT EXISTS pet_cosmetics (
  fm_id        TEXT PRIMARY KEY,
  equipped     TEXT NOT NULL DEFAULT '{}',  -- JSON: {slot: item_key}
  rename_count INTEGER NOT NULL DEFAULT 0   -- renames used (first is free)
);
"""


def ensure_shop_schema(db):
    for stmt in SHOP_SCHEMA.strip().split(";"):
        stmt = stmt.strip()
        if stmt:
            db._exec(stmt)


# --- catalog helpers ----------------------------------------------------------
def _bypass_items():
    """Bypass items are generated from the locked species registry so the
    shop can never drift out of sync with it."""
    import pets  # deferred: pets.py imports this module
    out = {}
    for key in pets.LOCKED_SPECIES:
        if pets.LOCKED_SPECIES[key].get("type") == "identity":
            # One-of-one species are bonded to a single identity — the shop
            # can never sell a way around that.
            continue
        spec = pets.PET_SPECIES[key]
        out[f"bypass:{key}"] = {
            "name": f"Unlock {spec['name']}",
            "kind": "bypass",
            "species": key,
            "price": BYPASS_PRICE,
            "description": (f"Skip the quest: adopt the {spec['kind']} "
                            f"without meeting its unlock condition. "
                            f"({pets.species_unlock_condition(key)})"),
        }
    return out


def catalog():
    """Full item catalog: static items + generated bypass items."""
    items = dict(SHOP_ITEMS)
    items.update(_bypass_items())
    return items


def items_for_api(db=None, fm_id=None):
    """Public catalog; when fm_id is given, annotate owned/equipped."""
    owned = set()
    equipped = {}
    if db is not None and fm_id:
        ensure_shop_schema(db)
        owned = {r["item"] for r in
                 db._q("SELECT item FROM shop_purchases WHERE fm_id=?", (fm_id,))}
        equipped = _equipped(db, fm_id)
    out = []
    for key, item in catalog().items():
        entry = {"key": key, **item}
        if fm_id:
            entry["owned"] = key in owned
            if item["kind"] == "accessory":
                entry["equipped"] = equipped.get(item["slot"]) == key
        out.append(entry)
    return out


# --- balances -----------------------------------------------------------------
def gross_spent(db, fm_id):
    ensure_shop_schema(db)
    r = db._one("SELECT COALESCE(SUM(price),0) s FROM shop_purchases"
                " WHERE fm_id=?", (fm_id,))
    return r["s"]


def spendable(db, fm_id):
    """Spendable balance = gross lifetime earned − gross shop spent.
    Lifetime (rewards ledger) is never touched by the shop."""
    return db.lifetime_points(fm_id) - gross_spent(db, fm_id)


def balance(db, fm_id):
    lifetime = db.lifetime_points(fm_id)
    spent = gross_spent(db, fm_id)
    return {"lifetime": lifetime, "spent": spent,
            "spendable": lifetime - spent}


# --- cosmetics ------------------------------------------------------------------
def _cosmetics(db, fm_id):
    ensure_shop_schema(db)
    row = db._one("SELECT equipped, rename_count FROM pet_cosmetics"
                  " WHERE fm_id=?", (fm_id,))
    if not row:
        db._exec("INSERT OR IGNORE INTO pet_cosmetics (fm_id) VALUES (?)",
                 (fm_id,))
        return {"equipped": {}, "rename_count": 0}
    try:
        equipped = json.loads(row["equipped"] or "{}")
    except (ValueError, TypeError):
        equipped = {}
    return {"equipped": equipped, "rename_count": row["rename_count"]}


def _equipped(db, fm_id):
    return _cosmetics(db, fm_id)["equipped"]


def equipped_accessories(db, fm_id):
    """Ordered list of equipped accessory item keys (for pet portraits)."""
    eq = _equipped(db, fm_id)
    return [eq[s] for s in sorted(eq)]


def owns(db, fm_id, item):
    ensure_shop_schema(db)
    return db._one("SELECT id FROM shop_purchases WHERE fm_id=? AND item=?",
                   (fm_id, item)) is not None


def has_species_bypass(db, fm_id, species):
    return owns(db, fm_id, f"bypass:{species}")


# --- buying ---------------------------------------------------------------------
def buy(db, fm_id, item, idempotency_key=None):
    """Buy a shop item. Signed, server-side, idempotent.

    Returns {"charged": price, "already_owned": bool, "spendable": n}.
    Raises ValueError on unknown item, insufficient funds, or (for
    consumables without a key) nothing — each purchase is its own row.
    """
    ensure_shop_schema(db)
    items = catalog()
    if item not in items:
        raise ValueError(f"unknown shop item: {item}")
    spec = items[item]
    price = spec["price"]

    one_time = spec["kind"] in ("accessory", "bypass")
    ref_id = item if one_time else (idempotency_key or
                                    f"rename_token:{now()}")
    # Idempotent retry BEFORE the funds check: a retry that arrives after
    # a successful purchase must return the original success, not 402 —
    # the first purchase already reduced the spendable balance.
    # (The IntegrityError fallback below still covers a lost race with an
    # in-flight twin.)
    prior = db._one(
        "SELECT item FROM shop_purchases WHERE fm_id=? AND ref_id=?",
        (fm_id, ref_id))
    if prior:
        return {"charged": 0, "already_owned": True,
                "spendable": spendable(db, fm_id),
                "item": prior["item"],
                "name": items.get(prior["item"], {}).get("name",
                                                         prior["item"])}

    if one_time and owns(db, fm_id, item):
        return {"charged": 0, "already_owned": True,
                "spendable": spendable(db, fm_id),
                "item": item, "name": spec["name"]}

    if spendable(db, fm_id) < price:
        raise ValueError(
            f"insufficient spendable Signal — {spec['name']} costs {price}, "
            f"you have {spendable(db, fm_id)} spendable")

    try:
        db._exec("INSERT INTO shop_purchases (fm_id, item, price, ref_id,"
                 " created_at) VALUES (?,?,?,?,?)",
                 (fm_id, item, price, ref_id, now()))
    except sqlite3.IntegrityError:
        # lost a race with an identical in-flight purchase: treat as no-op
        return {"charged": 0, "already_owned": True,
                "spendable": spendable(db, fm_id),
                "item": item, "name": spec["name"]}

    if spec["kind"] == "accessory":
        _equip(db, fm_id, item)

    return {"charged": price, "already_owned": False,
            "spendable": spendable(db, fm_id),
            "item": item, "name": spec["name"]}


def _equip(db, fm_id, item):
    """Equip an owned accessory into its slot (latest purchase wins)."""
    items = catalog()
    spec = items.get(item)
    if not spec or spec["kind"] != "accessory":
        raise ValueError("not an accessory")
    if not owns(db, fm_id, item):
        raise ValueError("you don't own that accessory")
    cos = _cosmetics(db, fm_id)
    eq = cos["equipped"]
    eq[spec["slot"]] = item
    db._exec("UPDATE pet_cosmetics SET equipped=? WHERE fm_id=?",
             (json.dumps(eq), fm_id))
    return equipped_accessories(db, fm_id)


def equip(db, fm_id, item):
    """Switch to another owned accessory (signed endpoint)."""
    return _equip(db, fm_id, item)


# --- rename tokens --------------------------------------------------------------
def use_rename(db, fm_id):
    """Consume rename allowance: the first rename is free; afterwards each
    rename costs one Rename Token. Raises ValueError when a token is owed
    but none is available. Returns 'first_free' or 'token'."""
    cos = _cosmetics(db, fm_id)
    if cos["rename_count"] == 0:
        db._exec("UPDATE pet_cosmetics SET rename_count=1 WHERE fm_id=?",
                 (fm_id,))
        return "first_free"
    tokens = db._one("SELECT COUNT(*) c FROM shop_purchases"
                     " WHERE fm_id=? AND item='rename_token'",
                     (fm_id,))["c"]
    used_after_first = cos["rename_count"] - 1
    if tokens <= used_after_first:
        raise ValueError("this rename needs a Rename Token — visit /shop")
    db._exec("UPDATE pet_cosmetics SET rename_count=rename_count+1"
             " WHERE fm_id=?", (fm_id,))
    return "token"


def rename_tokens_available(db, fm_id):
    cos = _cosmetics(db, fm_id)
    if cos["rename_count"] == 0:
        return "first rename free"
    tokens = db._one("SELECT COUNT(*) c FROM shop_purchases"
                     " WHERE fm_id=? AND item='rename_token'",
                     (fm_id,))["c"]
    return max(0, tokens - (cos["rename_count"] - 1))


# --- rules ----------------------------------------------------------------------
def shop_rules():
    items = [{"key": k, "name": v["name"], "kind": v["kind"],
              "price": v["price"],
              **({"slot": v["slot"]} if "slot" in v else {}),
              **({"species": v["species"]} if "species" in v else {})}
             for k, v in catalog().items()]
    return {
        "name": "Signal Shop",
        "version": SHOP_VERSION,
        "concept": ("Spend earned Signal on cosmetic Tidepal goods. Your "
                    "lifetime Signal NEVER decreases — the shop spends from "
                    "a separate spendable balance: gross earned minus gross "
                    "spent. Tiers, pet stages, and achievements always use "
                    "gross lifetime earned."),
        "items": items,
        "balance_rule": ("spendable = SUM(rewards.points) − "
                         "SUM(shop_purchases.price), computed server-side."),
        "anti_gaming": [
            "All buys are signed (musefm-v1) and server-side.",
            "Purchases are idempotent: UNIQUE(fm_id, ref_id) — a double-tap "
            "can never double-charge.",
            "Buying an owned accessory or bypass is a no-op, not a charge.",
            "No negative balances; insufficient funds fail cleanly.",
            "The purchase ledger is append-only — no refunds, no edits.",
        ],
    }
